# If enabled, shows an overlay on the HUD to help with cutting board slicing and combining recipes.
# Note: This is an experimental feature.
# Valid values: true, false
showCuttingBoardHelper = false
# The maximum distance that electricity nodes and connections can be seen by the camera.
# Valid range: 1 to 128 (inclusive)
electricityViewDistance = 48
# If enabled, displays a toast notification when another player rings one of your doorbells.
# Valid values: true, false
doorbellNotification = true

