
# Toilet related properties
[toilet]
	# The storage capacity of the fluid tank contained in this block. If you're using Forge,
	# 1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	# want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	# Valid range: 1 to 9223372036854775807 (inclusive)
	fluidCapacity = 1000
	# If enabled, when interacting with this block it will dispense free water into
	# it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	# capacity.
	# Valid values: true, false
	dispenseWater = true

# Kitchen Sink related properties
[kitchenSink]
	# The storage capacity of the fluid tank contained in this block. If you're using Forge,
	# 1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	# want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	# Valid range: 1 to 9223372036854775807 (inclusive)
	fluidCapacity = 3000
	# If enabled, when interacting with this block it will dispense free water into
	# it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	# capacity.
	# Valid values: true, false
	dispenseWater = true

# Electricity related properties
[electricity]
	# The maximum amount of links that can be connected to a single electricity node.
	# Valid range: 1 to 16 (inclusive)
	maximumLinksPerElectricityNode = 4
	# The maximum distance from one electricity node to another that a link can be made.
	# If this value is increased to a large value, it may result in an electricity node
	# being in an unloaded chunk. Electricity nodes in unloaded chunks won't be updated
	# even if the power does reach according to the maximumDaisyChain property.
	# Valid range: 1 to 64 (inclusive)
	maximumLinkDistance = 16.0
	# The maximum amount of nodes in a network that can be powered by an electricity
	# source, like the electricity generator.
	# Valid range: 1 to 512 (inclusive)
	maximumNodesInNetwork = 50
	# The maximum daisy chain that electricity can travel from a power source. A daisy chain
	# is electricity nodes connected one after the other to one or more other electricity
	# nodes. The larger this value is, the more processing time is required for updating
	# the power in an electricity network.
	# Valid range: 1 to 32 (inclusive)
	maximumDaisyChain = 8
	# The amount of power that is generated by the electricity generator per fuel tick.
	# For example, coal has 1600 ticks of fuel, and at a ratio of 4, it would produce
	# 6400 units of power. The default value of 8 means that the electricity generator
	# would consume almost 2 coal per in-game day.
	# Valid range: 1 to 128 (inclusive)
	fuelToPowerRatio = 8

# Trampoline related properties
[trampoline]
	# The maximum height that can be achieved from bouncing on the trampoline. The maximum
	# height is affected the shape of the trampoline, the center trampoline in a 3x3 will
	# be able to reach the maximum bounce height, while a single trampoline will only reach
	# half.
	# Valid range: 0 to 64 (inclusive)
	maxBounceHeight = 8.0

# Basin related properties
[basin]
	# If enabled, when interacting with this block it will dispense free water into
	# it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	# capacity.
	# Valid values: true, false
	dispenseWater = true
	# The storage capacity of the fluid tank contained in this block. If you're using Forge,
	# 1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	# want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	# Valid range: 1 to 9223372036854775807 (inclusive)
	fluidCapacity = 1000

# Mailing related properties
[mailing]
	# The maximum amount of items that can be queued for delivery to a mailbox. Items become
	# queued when the receiving mailbox's inventory is full. This is to prevent infinite storage.
	# Valid range: 0 to 256 (inclusive)
	deliveryQueueSize = 32
	# If enabled, this will ban items with an inventory (like a Shulker Box) being sent through
	# a Post Box. This prevents players from creating massive NBT on a single item, which can
	# cause issues for your server/world save.
	# Valid values: true, false
	banSendingItemsWithInventories = true
	# The amount of inventory rows in a mailbox. If you change this value from a larger to
	# a smaller value, items contained in the removed rows will be deleted. Use caution
	# when changing this value to avoid inconvenience and backup your saves.
	# Valid range: 1 to 6 (inclusive)
	mailboxInventoryRows = 1
	# The maximum amount of mailboxes a player is allowed to register/own.
	# Valid range: 1 to 2147483647 (inclusive)
	maxMailboxesPerPlayer = 16
	# Prevents items contained in this list from being sent through a Post Box.
	# An example of how the list is defined:
	# bannedItems = [
	#     "minecraft:water_bucket",
	#     "minecraft:diamond",
	#     "refurbished_furniture:mailbox"
	#     ...
	# ]
	# ^ Note: This is just an example. Write your list below.
	bannedItems = []

# Bath related properties
[bath]
	# The storage capacity of the fluid tank contained in this block. If you're using Forge,
	# 1000 units represents the capacity of a bucket, while it's 81000 on Fabric. So if you
	# want 3 buckets worth of storage, it will be 3000 (Forge) or 243000 (Fabric)
	# Valid range: 1 to 9223372036854775807 (inclusive)
	fluidCapacity = 10000
	# If enabled, when interacting with this block it will dispense free water into
	# it's fluid tank, assuming the tank is empty or contains water but has not reached it's
	# capacity.
	# Valid values: true, false
	dispenseWater = true

# Recycle Bin related properties
[recycleBin]
	# The base chance for the items created from recycling an item to be added to the output.
	# Recycled items are still consumed even if no items were added to the output. This value
	# is seen as the base value, however it is further affected for items that are damaged,
	# which greatly reduce the chance of an output. The value must be between 0 and 1 (inclusive)
	# Valid range: 0 to 1 (inclusive)
	baseOutputChance = 0.6
	# If enabled, the count of an item created from recycling will be randomized based on
	# the count defined in the recipe. For example, if the recipe is outputting 5 iron ingots,
	# a randomized output count will be a random number from 1 to 5
	# Valid values: true, false
	randomizeOutputCount = false
	# When enabled, the recycle bin will recycle every item even if the item doesn't recycle into anything.
	# Valid values: true, false
	recycleEveryItem = true
	# The amount of time in ticks that it takes to perform one cycle of recycling
	# Valid range: 1 to 2147483647 (inclusive)
	processingTime = 10

