
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.jade]
		enable_compat_jade = true

	[Compatibility.toughasnails]
		enable_compat_toughasnails = true
		#Limit thirst for vampires
		disableThirst = true

