
[Villagers]
	#Wearing a Dark Robe, along with variants, causes Villagers around the Player to have a negative Reputation unless said Player has 25 or more reputation among them, Default: false
	villagerHate = false
	#Villagers have a chance of converting into Warlocks if they're underneath a Block of Crying Obsidian, Default: true
	villagerConvertToWarlock = true
	#Having an owned Ravaged or Ravager, causes Villagers around the Player to have a negative Reputation, Default: false
	villagerHateRavager = false
	#Casting Spell in the presence of Villagers will cause the Player to lose a number of Reputation, set 0 to disable, Default: 0
	#Range: > 0
	villagerHateSpells = 0

[Misc]
	#Whether Goety Mobs can spawn in Overworld-like modded dimensions, Default: false
	interDimensionalMobs = false
	#Whether Wraiths should teleport towards their targets if they can't see them instead of just teleporting away when they're near them, Default: true
	wraithAggressiveTeleport = true
	#Whether Mobs with Tall Heads(ie. Villagers, Illagers, etc.) will drop Tall Skulls, Default: true
	tallSkullDrop = true
	#Spawn Weight for Wraith, Default: 20
	#Range: > 0
	wraithSpawnWeight = 20
	#Spawn Weight for Warlock, Default: 5
	#Range: > 0
	warlockSpawnWeight = 5

	[Misc.Apostle]
		#Gives Apostle an even more fancier death animation, Default: false
		fancierApostleDeath = false
		#Nether Meteors deals environmental damage. WARNING: Causes lots of lag. Default: false
		apocalypseMode = false

	[Misc.Vizier]
		#Viziers spawn Vexes instead of Irks, Default: false
		vizierMinion = false

[Servants]
	#How many seconds it takes before Ravager can manually roar again, Default: 10
	#Range: > 0
	ravagerRoarCooldown = 10
	#Mobs will automatically be hostile to servants, if servant is hostile towards the mob, Default: true
	mobSense = true
	#Whether Servants can attack Creepers if Mob Griefing Rule is False, Default: true
	servantsAttackCreepers = true
	#Owners can't attack or hurt their servants, Default: true
	ownerAttackCancel = true
	#Whether Servants or their owner are immune to attacks made by other servants that are summoned by the same owner, Default: true
	servantsMasterImmune = true
	#Whether creating a Redstone Golem causes the mold to change blocks, Default: true
	redstoneGolemMold = true
	#Whether Vex Servants can teleport to Players, Default: true
	vexTeleport = true

	[Servants."Undead Servants"]
		#How frequent Undead Servants heal, count seconds, Default: 1
		#Range: > 0
		undeadServantsHealTime = 1
		#Whether Undead Servants can teleport to Players, Default: false
		undeadTeleport = false
		#Chance that a zombie (or subclass) servant is summoned as a baby, Default: 0.05
		#Range: 0.0 ~ 1.0
		zombieServantBabyChance = 0.05
		#Whether Servants can attack Undead mobs if owner wears a full Necro Set, Default: false
		necroRobeUndead = false
		#How much Soul Energy it cost per second for an Undead Servant to heal, Default: 5
		#Range: > 0
		undeadServantsHealCost = 5
		#Whether Undead Servants can heal if summoned while wearing Necro Cape, Default: true
		undeadServantsHeal = true
		#How much Health Undead Servants heal, numerically, Default: 0.5
		#Range: 0.0 ~ 1.7976931348623157E308
		undeadServantsHealAmount = 0.5

[Illagers]
	#Whether Enviokers, Inquillagers and Conquillagers can steal Totems of Souls or Totems of Undying, Default: true
	illagerSteal = true
	#Whether Illague Effect can spread from non Conquillagers that has the effect, Default: true
	illagueSpread = true

	[Illagers."Illager Assaults"]
		#Spawn Frequency for Illagers Hunting the Player, Default: 12000
		#Range: > 0
		illagerAssaultSpawnFreq = 12000
		#The maximum amount of Soul Energy the Player has that is taken consideration for the Assaults, Default: 30000
		#Range: > 0
		illagerAssaultLimit = 30000
		#Spawn Chance for Illagers Hunting the Player every Spawn Frequency, the lower the more likelier, Default: 5
		#Range: > 0
		illagerAssaultSpawnChance = 5
		#Hitting the Illager Assault Limit of Soul Energy have a chance of giving Player Bad Omen effect, Default: true
		soulEnergyBadOmen = true
		#Modded Illagers Spawning based of Player's Soul Energy amount, Default: true
		illagerAssault = true
		#How much Soul Energy the Player has is required for Special Illagers to spawn, Default: 2500
		#Range: > 0
		illagerAssaultThreshold = 2500

	[Illagers.Raid]
		#Whether Preachers appear in Raids, Default: true
		preacherRaid = true
		#Whether Conquillagers appear in Raids, Default: true
		conquillagerRaid = true
		#Whether Pikers appear in Raids, Default: true
		pikerRaid = true
		#Whether Warlocks appear in Raids, Default: true
		warlockRaid = true
		#Whether Enviokers appear in Raids, Default: true
		enviokerRaid = true
		#Whether Modded Illagers appears in Raids, Default: true
		specialIllagerRaid = true
		#Whether Armored Ravagers spawn in Raids, Default: true
		armoredRavagerRaid = true
		#Whether Inquillagers appear in Raids, Default: true
		inquillagerRaid = true
		#Whether Hostile Redstone Golems appear in Raids, Default: false
		hostileRedstoneGolemRaid = false
		#Whether Ministers appear in Raids, Default: true
		ministerRaid = true

[Textures]
	#If certain mobs have a different texture during some holiday months, Default: true
	holidaySkins = true

	[Textures."Summoned Mobs"]

		[Textures."Summoned Mobs"."Wraith Servants"]
			#If Wraith Servants have custom textures, Default: true
			wraithServantTexture = true

		[Textures."Summoned Mobs"."Zombie Servants"]
			#If Jungle Zombie Servants have custom textures, Default: true
			jungleZombieServantTexture = true
			#If Husk Servants have custom textures, Default: true
			huskServantTexture = true
			#If Zombie Servants have custom textures, Default: true
			zombieServantTexture = true
			#If Drowned Servants have custom textures, Default: true
			drownedServantTexture = true
			#If Frozen Zombie Servants have custom textures, Default: true
			frozenZombieServantTexture = true

		[Textures."Summoned Mobs"."Skeleton Servants"]
			#If Sunken Skeleton Servants have custom textures, Default: true
			sunkenSkeletonServantTexture = true
			#If Vanguard Servants have custom textures, Default: true
			vanguardServantTexture = true
			#If Skeleton Servants have custom textures, Default: true
			skeletonServantTexture = true
			#If Mossy Skeleton Servants have custom textures, Default: true
			mossySkeletonServantTexture = true
			#If Stray Servants have custom textures, Default: true
			strayServantTexture = true

		[Textures."Summoned Mobs".Vexes]
			#If Vexes have custom textures, Default: true
			vexTexture = true

		[Textures."Summoned Mobs"."Zombified Piglin Servants"]
			#If Zombified Piglin Servants have custom textures, Default: true
			zPiglinServantTexture = true

		[Textures."Summoned Mobs"."Redstone Golem"]
			#If Redstone Golems show cracks when damaged sufficiently, Default: false
			redstoneGolemCrack = false

