
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.eidolon]
				illwood = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.forbidden_arcanus]
				aurum = true
				edelwood = true

			[general.types.wood_type.primalmagick]
				sunwood = true
				moonwood = true
				hallowood = true

			[general.types.wood_type.born_in_chaos_v1]
				scorched = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.betterend]
				mossy_glowshroom = true
				pythadendron = true
				end_lotus = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				helix_tree = true
				umbrella_tree = true
				jellyshroom = true
				lucernia = true

			[general.types.wood_type.abyssal_decor]
				white_wood = true
				blackwood = true
				cinnamon = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.meadow]
				pine = true

			[general.types.wood_type.regions_unexplored]
				alpha = true
				baobab = true
				blackwood = true
				blue_bioshroom = true
				brimwood = true
				cobalt = true
				cypress = true
				dead = true
				eucalyptus = true
				green_bioshroom = true
				joshua = true
				kapok = true
				larch = true
				magnolia = true
				maple = true
				mauve = true
				palm = true
				pine = true
				pink_bioshroom = true
				redwood = true
				socotra = true
				willow = true
				yellow_bioshroom = true

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.vinery]
				grapevine = true
				cherry = true
				apple = true

			[general.types.leaves_type.caupona]
				walnut = true
				fig = true
				wolfberry = true

			[general.types.leaves_type.eidolon]
				illwood = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.forbidden_arcanus]
				aurum = true
				nuggety_aurum = true

			[general.types.leaves_type.primalmagick]
				hallowood = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.betterend]
				pythadendron = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				lucernia = true

			[general.types.leaves_type.abyssal_decor]
				cinnamon = true
				flowering_cinnamon = true

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.meadow]
				pine = true

			[general.types.leaves_type.regions_unexplored]
				bamboo = true
				golden_larch = true
				alpha = true
				apple_oak = true
				baobab = true
				blackwood = true
				magnolia = true
				cypress = true
				dead = true
				dead_pine = true
				eucalyptus = true
				flowering = true
				kapok = true
				larch = true
				maple = true
				mauve = true
				orange_maple = true
				palm = true
				pine = true
				blue_magnolia = true
				pink_magnolia = true
				redwood = true
				red_maple = true
				brimwood = true
				enchanted_birch = true
				small_oak = true
				silver_birch = true
				socotra = true
				white_magnolia = true
				willow = true
				ashen = true

		[general.types.cake]

			[general.types.cake.createaddition]
				chocolate_cake = true
				honey_cake = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.friendsandfoes]
				beehive = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.mcwwindows]
				stripped_log_window2 = true
				log_parapet = true
				window2 = true
				plank_window = true
				louvered_shutter = true
				stripped_log_four_window = true
				four_window = true
				plank_window2 = true
				plank_parapet = true
				blinds = true
				window = true
				pane_window = true
				shutter = true
				plank_pane_window = true
				stripped_pane_window = true
				plank_four_window = true
				stripped_log_window = true

			[general.entries.wood_type.mcwdoors]
				beach_door = true
				nether_door = true
				stable_head_door = true
				barn_door = true
				mystic_door = true
				japanese2_door = true
				waffle_door = true
				tropical_door = true
				barn_glass_door = true
				cottage_door = true
				four_panel_door = true
				japanese_door = true
				western_door = true
				bark_glass_door = true
				paper_door = true
				classic_door = true
				bamboo_door = true
				swamp_door = true
				glass_door = true
				stable_door = true
				modern_door = true

			[general.entries.wood_type.refurbished_furniture]
				storage_cabinet = true
				storage_jar = true
				kitchen_cabinetry = true
				crate = true
				desk = true
				chair = true
				light_ceiling_fan = true
				cutting_board = true
				drawer = true
				table = true
				mail_box = true
				dark_ceiling_fan = true
				kitchen_sink = true
				toilet = true
				lattice_fence = true
				basin = true
				kitchen_drawer = true
				lattice_fence_gate = true
				bath = true
				kitchen_storage_cabinet = true

			[general.entries.wood_type.regions_unexplored]
				branch = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.refurbished_furniture]
				hedge = true

